### ISSUE TITLE
提供渲染功能，可实现锁屏、壁纸和主题设计的动态效果。

### ISSUE THREAD

**Issue by bobo19870225** [HMS-Core/hms-image-render-java#1]
如题，这是官方提到的有这个功能，我仔细看了demo以及文档，并没有找到相关内容，sdk里直接返回一个直接渲染好了的view，这在动态壁纸里是无法使用的。

**Comment by Mike-mei** [comment]
要实现动态壁纸，需要根据我们xml脚本编写规则生成特定的动态view，然后把这个view添加到动态壁纸中即可，可参考[文档](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides-V5/xml-introduction-0000001050439245-V5)

**Comment by bobo19870225** [comment]
您好，谢谢您的解答，我的问题出现在第二步“把这个view添加到动态壁纸中”，动态壁纸的写法中我只能拿到SurfaceHolder 的对象，然后通过Canvas canvas = surfaceHolder.lockCanvas();拿到canvas，调用生成的动态view的.draw(canvas)方法去绘制，最后调用 surfaceHolder.unlockCanvasAndPost(canvas);显示view，但是结果黑屏了，我实现的代码如下，希望大神指点一二或者出个动态壁纸的demo，感激不尽。

public class MyLwp extends WallpaperService {
    @Override
    public Engine onCreateEngine() {
        return new MyEngine(getApplicationContext());
    }

    class MyEngine extends Engine {
        private static final String TAG = "MyEngine";
        private ImageRenderImpl imageRenderAPI;
        private final Context context;

        public MyEngine(Context applicationContext) {
            context = applicationContext;
        }

        @Override
        public SurfaceHolder getSurfaceHolder() {
            return super.getSurfaceHolder();
        }

        private String sourcePath;

        @Override
        public void onCreate(SurfaceHolder surfaceHolder) {
            sourcePath = getFilesDir().getPath() + File.separator + SOURCE_PATH;
//            canvas.drawColor(Color.RED);
            super.onCreate(surfaceHolder);
        }

        /**
         * Use the ImageRender API.
         */
        private void initImageRender(final SurfaceHolder surfaceHolder) {
            // Obtain an ImageRender object.
            ImageRender.getInstance(context, new ImageRender.RenderCallBack() {
                @Override
                public void onSuccess(ImageRenderImpl imageRender) {
                    Log.i(TAG, "getImageRenderAPI success");
                    if (!Utils.copyAssetsFilesToDirs(context, "WaterWallpaper", sourcePath)) {
                        Log.e(TAG, "copy files failure, please check permissions");
                        return;
                    }
                    imageRenderAPI = imageRender;
                    addView(surfaceHolder);
                }

                @Override
                public void onFailure(int i) {
                    Log.e(TAG, "getImageRenderAPI failure, errorCode = " + i);
                }
            });
        }

        private void addView(SurfaceHolder surfaceHolder) {
            // Initialize the ImageRender object.
            int initResult = imageRenderAPI.doInit(sourcePath, Utils.getAuthJson());
            Log.i(TAG, "DoInit result == " + initResult);
            if (initResult == 0) {
                // Obtain the rendered view.
                RenderView renderView = imageRenderAPI.getRenderView();
                if (renderView.getResultCode() == ResultCode.SUCCEED) {
                    View view = renderView.getView();
                    if (null != view) {
                        // Add the rendered view to the layout.
//                        contentView.addView(view);
//                        hashCode = String.valueOf(view.hashCode());
                        Canvas canvas = surfaceHolder.lockCanvas();
//                        canvas.drawColor(Color.RED);
                        view.draw(canvas);
                        view.invalidate();
                        surfaceHolder.unlockCanvasAndPost(canvas);
                    } else {
                        Log.w(TAG, "GetRenderView fail, view is null");
                    }
                } else if (renderView.getResultCode() == ResultCode.ERROR_GET_RENDER_VIEW_FAILURE) {
                    Log.w(TAG, "GetRenderView fail");
                } else if (renderView.getResultCode() == ResultCode.ERROR_XSD_CHECK_FAILURE) {
                    Log.w(TAG, "GetRenderView fail, resource file parameter error, please check resource file.");
                } else if (renderView.getResultCode() == ResultCode.ERROR_VIEW_PARSE_FAILURE) {
                    Log.w(TAG, "GetRenderView fail, resource file parsing failed, please check resource file.");
                } else if (renderView.getResultCode() == ResultCode.ERROR_REMOTE) {
                    Log.w(TAG, "GetRenderView fail, remote call failed, please check HMS service");
                } else if (renderView.getResultCode() == ResultCode.ERROR_DOINIT) {
                    Log.w(TAG, "GetRenderView fail, init failed, please init again");
                }
            } else {
                Log.w(TAG, "Do init fail, errorCode == " + initResult);
            }
        }

        @Override
        public void onDestroy() {
            if (null != imageRenderAPI) {
                imageRenderAPI.removeRenderView();
            }
            super.onDestroy();
        }

        @Override
        public void onSurfaceChanged(SurfaceHolder holder, int format, int width, int height) {
            super.onSurfaceChanged(holder, format, width, height);
        }

        @Override
        public void onSurfaceCreated(SurfaceHolder holder) {
            initImageRender(holder);
            super.onSurfaceCreated(holder);
        }

        @Override
        public void onSurfaceDestroyed(SurfaceHolder holder) {
            super.onSurfaceDestroyed(holder);
        }
    }
}

**Comment by Mike-mei** [comment]
1. 首先建议先检查一下拿到的view是不是正确的
2. 可以尝试把以下这一段代码：

```
Canvas canvas = surfaceHolder.lockCanvas();
// canvas.drawColor(Color.RED);
view.draw(canvas);
view.invalidate();
surfaceHolder.unlockCanvasAndPost(canvas);
```

替换成：
```
Canvas canvas = surfaceHolder.lockCanvas();
canvas.save();
view.draw(canvas);
canvas.restore();
surfaceHolder.unlockCanvasAndPost(canvas);
```
